name: Build and Test

on: push

jobs:
  build-and-test:
    runs-on: ubuntu-20.04
    container: 
      image: ros:melodic
  
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          path: src/lanelet2_cs_converter
      - name: Checkout llh_converter
        uses: actions/checkout@v2
        with:
          repository: MapIV/llh_converter
          path: src/llh_converter

      -run: |
        pwd
        ls -la
